### ISSUE TITLE
環境構築（ハマべさん）

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-azalea#1]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by hamabehayato** [comment]
![Uploading スクリーンショット 2021-05-01 22.36.22.png…]()

**Comment by hamabehayato** [comment]
<img width="904" alt="スクリーンショット 2021-05-01 22 36 22" src="https://user-images.githubusercontent.com/66937941/116786520-16f9e380-aada-11eb-9025-0fe57b7db366.png">

**Comment by yuki-tachi0219** [comment]
OKです！
これで完了とさせていただきます。
