### ISSUE TITLE
DB構築 Migration Users関連

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-azalea#12]
migrationファイルを作って、DB構造を決める
rails db:migrate を実行して、db/schema.rbを作成すること
DB構造は、GoogleドライブのER図を参考にすること

データ型の読み方はこちら
https://qiita.com/vermilionfog/items/816fa7de1d0213979929#対応表

db/schema.rb のUserに関する部分をスクショして添付すること

**Comment by yuzumotishun** [comment]
#12 レビューお願いします。
間違っているかどうかも分からなかったため、一旦投げさせていただきます。
railsチュートリアルをもう一度さらっと見返してきます💨

![スクリーンショット 2021-05-02 23 06 56](https://user-images.githubusercontent.com/78217764/116816930-0d867f00-ab9f-11eb-965b-62f928749811.png)

**Comment by yuki-tachi0219** [comment]
`t.integer "user_classification_id"` がちょっと怪しいです。
userのマイグレーションファイルにて`t.references :user_classification`と書く必要があるのですが、うまくいってますでしょうか。
