### ISSUE TITLE
データ投入 Seed Products関連

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#17]
db/seeds.rb にProduct関係の仮データを入れること

2人のユーザーに対して2つずつProductを作成すること。
seedを実行することで、合計4つのProductが生成されるようにすること。

コンソール上で
rails db:seed
を実行して、rails console上でデータが正しく作られたかどうか確認する。

rails console上で Product.all を実行 → Product一覧が出てくる。これをスクショして添付すること。

**Comment by hamabehayato** [comment]
<img width="722" alt="スクリーンショット 2021-05-05 7 56 33" src="https://user-images.githubusercontent.com/66937941/117080285-77a64c00-ad78-11eb-9a7a-1798bdbdec46.png">
