### ISSUE TITLE
環境構築（さっしゅんさん）

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-azalea#2]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by yuzumotishun** [comment]
#2 完了しました！
「Dockerコンテナが正常に起動しない問題」が発生しましたが、READMEの記載どおりに実行しました。
ご確認お願いします。
![スクリーンショット 2021-05-02 12 37 54](https://user-images.githubusercontent.com/78217764/116801276-3b3dda80-ab43-11eb-9afd-566caa8ed447.png)

**Comment by yuki-tachi0219** [comment]
完璧です ✨
これで完了といたします！！
