### ISSUE TITLE
ユーザー情報画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#23]
path: /users/:id
controller#action: Users#show
参考モックアップ: user_info.html

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by yuzumotishun** [comment]
#23 夜分遅くにすいません。showアクションに対応する画面を作成しました。（右にずれている気がしますが仕様ではないですよね、、？）
![スクリーンショット 2021-05-05 3 26 18](https://user-images.githubusercontent.com/78217764/117052201-68140c80-ad52-11eb-9806-8999cf95c0ce.png)

**Comment by yuzumotishun** [comment]
show画面作成しました。ですが、以下画像のようにユーザー情報の中身が右にずれてしまってます。ググっても解決に至らなそうだったので、ヒント等いただけたら幸いです。
![スクリーンショット 2021-05-05 23 45 44](https://user-images.githubusercontent.com/78217764/117160768-5c7d2000-adfc-11eb-98a2-9a07fed6b60f.png)
@TAKO-zhangyu @yuki-tachi0219
