### ISSUE TITLE
プルリク説明動画視聴、READMEに氏名記入（ハマベさん）

### ISSUE THREAD

**Issue by quest-academia** [quest-academia/qa-rails-ec-training-azalea#3]
プルリク説明動画の通りにリポジトリを自身のPCに取り込み、READMEを修正した状態でプルリクエストを提出すること。
プルリクが承認されてマージされたら完了とする。

**Comment by hamabehayato** [comment]
![Uploading スクリーンショット 2021-05-01 22.36.22.png…]()
