### ISSUE TITLE
注文詳細画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#30]
path: /orders/:id
controller#action: Orders#show
参考モックアップ: order_details.html, order_details2.html

URLで指定したidを持つ注文がある場合は、その注文の情報を表示(order_details.html)
注文が存在しない場合は、「該当の注文は見つかりませんでした」と表示(order_details2.html)

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by hamabehayato** [comment]
![スクリーンショット 2021-05-19 14 16 47](https://user-images.githubusercontent.com/66937941/118759960-efae5f00-b8ac-11eb-92a5-94b4e716ebfa.png)

**Comment by hamabehayato** [comment]
![スクリーンショット 2021-05-19 14 16 58](https://user-images.githubusercontent.com/66937941/118759991-fccb4e00-b8ac-11eb-9714-a10f250d1554.png)
