### ISSUE TITLE
認可処理機能

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#37]
ログインしていない場合、users#show, editページを見れないようにして自動的にログインページに遷移するよう、sessions_helper.rbに実装すること。
メソッド名はlogged_in_user
フラッシュメッセージは「ログインしてください。」

ログインしていたとしても、他人に関係するページは見れないようにして、自動的にroot_pathに遷移するよう、sessions_helper.rb に実装。
メソッド名はcorrect_user
フラッシュメッセージは「他人の情報にアクセスすることはできません。」

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by hamabehayato** [comment]
![Uploading スクリーンショット 2021-05-17 16.14.27.png…]()

**Comment by hamabehayato** [comment]
![Uploading スクリーンショット 2021-05-17 16.11.13.png…]()
