### ISSUE TITLE
商品検索画面(検索ロジック以外)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#39]
path: /products
controller#action: Products#index
参考モックアップ: products_index.html(商品がある場合),products_index_not_found.html(商品がない場合) 

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

検索機能は除き、最初から全商品が表示されている状態にすること。
ページネーション機能は、kaminari gemを使うこと。
参考：https://qiita.com/d_nagano1002/items/fd90340c50324e845fe1

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by TAKURO-8716** [comment]
- [ ] productsコントローラーにindexアクションを作成  　/インスタンス変数を設定する
- [ ] ルーティングを設定  get 'products', to: 'products#index' 　（←resourcesが書かれているので必要ない）
- [ ] 参考モックアップをもとにproductsフォルダの中にindex.html.erbファイルを作成する  　/eachメソッドを使う
- [ ] kaminari gemを使いページネーション機能を実装する

**Comment by TAKURO-8716** [comment]
kaminariについての質問です。
どれだけのレコードが表示されたらページを増やせばいいでしょうか？

**Comment by yuki-tachi0219** [comment]
>どれだけのレコードが表示されたらページを増やせばいいでしょうか？

15件でお願いします。
画面定義書に「商品15件ごとにページを分ける」と書いてあるので。

**Comment by TAKURO-8716** [comment]
かしこまりました。

**Comment by TAKURO-8716** [comment]
seedの修正やkaminariの実装など完了いたしました。
ご確認お願いいたします。

**Comment by TAKURO-8716** [comment]
予想時間
6時間

かかった時間
約6~8時間

6/3(木)まで

完了した日
6/4(金)
