### ISSUE TITLE
TOPページ画面

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#40]
path: /
controller#action: StaticPages#home
参考モックアップ: home.html, home_after_login.html

ログインしているときとしていないときで表示画面を切り替えること。
リンク先が存在するものについては、リンクを設定すること。

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by hamabehayato** [comment]
実作業時間 約2時間

**Comment by hamabehayato** [comment]
![スクリーンショット 2021-05-21 9 44 57](https://user-images.githubusercontent.com/66937941/119065841-68cac500-ba19-11eb-9d25-c8d131eae5a7.png)

ログインしていない時

**Comment by hamabehayato** [comment]
![スクリーンショット 2021-05-21 9 45 13](https://user-images.githubusercontent.com/66937941/119065868-7b44fe80-ba19-11eb-9b62-fca1790a1593.png)

ログインしている時

**Comment by hamabehayato** [comment]
<img width="1344" alt="スクリーンショット 2021-05-21 9 51 55" src="https://user-images.githubusercontent.com/66937941/119066217-42595980-ba1a-11eb-922c-de0000564981.png">

ログインしている時

**Comment by yuki-tachi0219** [comment]
OKです 👌
