### ISSUE TITLE
ユーザー登録ページ、登録処理

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#41]
登録ページ
path: GET /signup
controller#action: Users#new
参考モックアップ: sign_up.html

登録処理
path: POST /signup
controller#action: Users#create

登録後のリダイレクト先については画面定義書参照
登録に成功したら「ユーザーを登録しました。こちらからログインしてください。」というフラッシュメッセージを出すこと
登録に失敗したら、問題箇所を指摘するメッセージを表示すること。ユーザー修正画面と同様に実装すればOK

対応するコントローラとアクションを作成すること
参考モックアップをもとにhtml.erbファイルを作成すること。

**Comment by yuzumotishun** [comment]
- [ ] ユーザー登録ページの作成
* routesにpath: GET /signupを指定
* コントローラにnew作成
* new.html.erb作成
- [ ] 登録処理
* routesにpath: POST /signupを指定
* コントローラにcreateを定義
* 登録が成功時、フラッシュメッセージとともにlogin画面にリダイレクト
* 登録が失敗時、エラーメッセージとともにrenderでnewページに返す
- [ ] 動作確認
- [ ] プルリクを出す

予想完了時間 : 3時間
納期 : 5/23

**Comment by yuki-tachi0219** [comment]
問題なさそうなので、そのまま進めていきましょう！！

**Comment by yuzumotishun** [comment]
実質対応時間：7.5h
