### ISSUE TITLE
ヘッダー修正

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#42]
ログイン時、ログアウト時で表示を切り替えること
リンク先ページがあるものについてすべてリンクを有効にすること
ログイン時にヘッダーに名前を表示すること

ページが表示されたらスクリーンショットを保存し、ここに貼り付けて報告すること。

**Comment by hamabehayato** [comment]
- [ ] ヘッダーの修正

- ログイン時、ログアウト時で表示を切り替える
  - sessions_helper の logged_in? メソッドがすでにあるから、簡単に実装できそう。
- ログイン時にヘッダーに名前を表示すること
  - これは、すでに実装されている。確か、#36 でテストがてら実装した。

- [ ] 動作確認
- [ ] プルリクを出す
 
予想完了時間 : 2時間
納期 : 5/25

**Comment by hamabehayato** [comment]
<img width="1243" alt="スクリーンショット 2021-05-23 18 59 56" src="https://user-images.githubusercontent.com/66937941/119255933-2eb81980-bbf9-11eb-9519-bcda5a202421.png">

非ログイン時

**Comment by hamabehayato** [comment]
<img width="1243" alt="スクリーンショット 2021-05-23 19 00 18" src="https://user-images.githubusercontent.com/66937941/119255957-442d4380-bbf9-11eb-9abd-12cc76623dcc.png">

ログイン時

**Comment by hamabehayato** [comment]
> 予想完了時間 : 2時間
> 納期 : 5/25

実作業時間：1時間
完了 ：5/24
