### ISSUE TITLE
ユーザー退会

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#43]
path: DELETE /users/:id
controller#action: users#destroy
退会をボタンを押したら、
「ユーザーデータが全て削除されます。本当に退会しますか？」
というダイアログボックスが開くようにすること

退会後、トップページに遷移すること
自動的にログアウト状態になっているか確認すること。

**Comment by hamabehayato** [comment]
## ユーザー退会機能の実装

- [ ] users コントローラに、destroy メソッドを作成
- [ ] users/edit.html.erb の退会ボタンを、link_to model: :delete のものに置き換え
- [ ] 自動的にログアウトするように実装

※routes は、resouces users ですでに存在しているので、ここで作成する必要なし

納期 6/9
予想 2時間

**Comment by hamabehayato** [comment]
<img width="1248" alt="スクリーンショット 2021-06-08 13 40 36" src="https://user-images.githubusercontent.com/66937941/121124020-30234c00-c85f-11eb-9d6e-98bd50d0ed25.png">

**Comment by hamabehayato** [comment]
<img width="1248" alt="スクリーンショット 2021-06-08 13 40 40" src="https://user-images.githubusercontent.com/66937941/121124059-3fa29500-c85f-11eb-9cf2-f93682694f85.png">
