### ISSUE TITLE
商品検索画面(検索ロジック)

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#44]
参考：https://qiita.com/yusuko/items/cff4e46aeafbc3beecf2
商品の商品名カラムに対して部分一致の検索をかけること。
検索キーワードがないときは、全商品を表示させること。

**Comment by yuki-tachi0219** [comment]
セレクトボックスに関する参考リンク：https://shinmedia20.com/rails-select-box

**Comment by TAKURO-8716** [comment]
~ 実装方針 ~

⚫︎商品の商品名カラムに対して部分一致の検索をかける
⚫︎検索ワードがないときは、全商品を表示させる

⚫︎「商品カテゴリ」のセレクトボックスにはseedのDBにあるものだけが表示されるようにする
⚫︎「商品カテゴリ」のセレクトボックスを選択したときにその商品カテゴリに絞って検索がかかるようにする

- [ ] methodをgetにし、form_tagを使って、検索formを表示する
- [ ] (params[:search])でformから検索ワードを受け取る（#Viewのformで取得したパラメータをモデルに渡す）
- [ ] ControllerやModelで、searchメソッドやwhereメソッドなどを使い、検索ワードを含むデータを出力する
- [ ] そのデータ（@posts）をviewに渡して埋め込む

- [ ] ビューヘルパーのselectメソッドを使ってセレクトボックスを作成する
- [ ] 「商品カテゴリ」のセレクトボックスを選択したときにその商品カテゴリに絞って検索がかかるようにする

予想時間
12時間

納期
6/8(火)まで

**Comment by yuki-tachi0219** [comment]
フォームはform_withでお願いします。Rails6からはform_withが推奨されているので。
カテゴリーの絞り込みも、paramsが使えそうです。params[:category_id]みたいな定義ができればいいですね。
