### ISSUE TITLE
環境構築(TAKUROさん)

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-azalea#48]
localhost:3000にアクセスして、「Yeh! You're on Rails!!」が表示されればOK
このissueに、「Yeh! You're on Rails!!」の画面をスクショして添付すること。
M1のMacの場合はローカル環境で構築、それ以外の場合はdockerを用いて環境構築すること。

**Comment by TAKURO-8716** [comment]
<img width="1440" alt="スクリーンショット 2021-05-04 15 30 57" src="https://user-images.githubusercontent.com/64839364/116967790-176ac800-acee-11eb-9f91-b3e3e8929cb5.png">

**Comment by yuki-tachi0219** [comment]
OKです！これで完了とさせていただきます 👍
