### ISSUE TITLE
注文キャンセル

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#61]
注文詳細画面にて、注文をキャンセルするボタンを押したら該当する注文を削除する。
order_details も連動して削除されるかどうか確認すること。
注文がキャンセルされたら、注文履歴ページに遷移させること

**Comment by yuzumotishun** [comment]
- [ ] 注文詳細画面にて、注文をキャンセルするボタンを押したら該当する注文を削除する。

* キャンセルボタン押下で`link_to order_path method: :delete`が走る
* orderコントローラ内にdeleteメソッドを作成
* deleteメソッド内部ではcurrent_user.orders.Findで該当orderを探し、delete

- [ ] order_details も連動して削除されるかどうか確認すること。
* orderモデルで`has_many :order_details, dependent: :destroy`の記述がすでにあるので、自動で消されるはず。確認する。

- [ ] 注文がキャンセルされたら、注文履歴ページに遷移させること
* 一連の処理が終わった後、deleteメソッド内の最後で`redirect_to 注文履歴ページ`
* 注文履歴のhtmlはまだ存在していないはずなので、注文履歴ページに飛ぶようにTODOに残しておいて、現状ではroot_pathに設定

予想完了時間: 6時間
納期6/15
