### ISSUE TITLE
カート機能

### ISSUE THREAD

**Issue by TAKO-zhangyu** [quest-academia/qa-rails-ec-training-azalea#62]
カートページ
path: POST carts/add_cart
controller#action: carts#show,
参考モックアップ: cart_list.html

削除処理
path: DELETE carts/destroy
controller#action: Users#create

カートへ商品を追加、削除する機能を実装。

注文確定のボタン押下後、注文情報をDBへ格納し、購入画面へ遷移

sessionを使用した実装にすること。

**Comment by yuzumotishun** [comment]
* モックアップを参考に
- [ ] カート内商品一覧画面の作成
- [ ] 購入画面の作成
- [ ] カート内に商品がない場合、購入画面で条件分岐し、「カートに商品はありません。」を表示
___
- [ ] session[:cart] に商品情報を与え、sessionを基にした商品の購入、削除機能を作成
___
* 削除ボタンを押下後
- [ ] カート内の該当する商品を削除
- [ ] 同画面にリダイレクト
* 注文確定ボタンを押下後、
- [ ] sessionを空にする。
- [ ] カート内を空にする。
- [ ] 購入完了画面を表示
- [ ] 注文番号の表示
___
- [ ] 動作確認
- [ ] rubocop実行
- [ ] プルリクを出す

予想完了時間 : 20時間
納期 : 6/1

**Comment by yuzumotishun** [comment]
実質対応時間: 60時間ほど
（見積もりが甘々の甘でした、、）
