### ISSUE TITLE
エラーメッセージの表示

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-azalea#74]
ユーザー登録やユーザー情報更新でバリデーションエラーが起きた時に、どんなバリデーションエラーが出たか表示すること
参考：https://qiita.com/d0ne1s/items/25acf0e70c12042c4c35

**Comment by TAKURO-8716** [comment]
エラーメッセージの表示　やること
-[ ] フォームの中に<%= render 'shared/error_messages', object: f.object %>と書き込む
-[ ] パーシャルでobject.errorsを使ってエラーメッセージを呼び出す

**Comment by TAKURO-8716** [comment]
エラーメッセージの表示　やること
-[ ]フォームの中に<%= render 'shared/error_messages', object: f.object %>と書き込む
-[ ]パーシャルでobject.errorsを使ってエラーメッセージを呼び出す

**Comment by TAKURO-8716** [comment]
エラーメッセージの表示　やること
- [ ] フォームの中に<%= render 'shared/error_messages', object: f.object %>と書き込む
- [ ] パーシャルでobject.errorsを使ってエラーメッセージを呼び出す

**Comment by TAKURO-8716** [comment]
<img width="1440" alt="スクリーンショット 2021-05-24 0 28 53" src="https://user-images.githubusercontent.com/64839364/119266763-06dfaa80-bc27-11eb-9289-5df0490cf0b8.png">
