### ISSUE TITLE
ゲストログイン

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-azalea#90]
就活などでサイトの中身を見せるために、ボタンひとつでログインできるようにしたい
参考：https://qiita.com/take18k_tech/items/35f9b5883f5be4c6e104

**Comment by hamabehayato** [comment]
## ゲストログイン機能の実装

- ゲストログイン機能の実装
  - [ ] sessionコントローラーに`guest_sign_in`メソッドを追加
  - [ ] ゲストユーザーを削除できないようにする
  - [ ] ゲストユーザーがメールアドレス・パスワードを変更できないようにする

- ゲストログインボタンの設置
  - [ ] ヘッダー、ログインボタンの横
  - [ ] TOP画面、ログインボタンの右
  - [ ] ログイン画面、ログインボタンの下

**Comment by yuki-tachi0219** [comment]
>ゲストユーザーがメールアドレス・パスワードを変更できないようにする

たしかにこれ大事ですね。変更削除できないようにするためにどんな実装をすればいいと思いますか？

**Comment by hamabehayato** [comment]
> > ゲストユーザーがメールアドレス・パスワードを変更できないようにする
> 
> たしかにこれ大事ですね。変更削除できないようにするためにどんな実装をすればいいと思いますか？

おそらく、
```
def "editページにアクセスしようとする"
  if ログインユーザがゲストユーザーである時、
    アラート"ゲストユーザでは変更できません"を表示
    root_pathにリダイレクトする
  end
end
```

みたいな感じかな、と思っております。

**Comment by hamabehayato** [comment]
あと、 'sessionコントローラーにguest_sign_inメソッドを追加'
と書いていますが、これは、`session helper`に書いた方が良いですかね。

ログイン状態は、全ページに渡って影響するものだから、そっちの方が良い気がしました。

**Comment by yuki-tachi0219** [comment]
変更を防ぐ処理やゲストログイン処理はhelperに書きましょう👍
